[window]
opacity = 0.97
blur = true
decorations_theme_variant = "Dark"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background = "#30302e"
foreground = "#a8b0b8"
dim_foreground = "#9098a0"
bright_foreground = "#e0e5ef"

[colors.cursor]
text = "#30302e"
cursor = "#528ab7"

[colors.vi_mode_cursor]
text = "#30302e"
cursor = "#b98a5c"

[colors.search]
matches = { foreground = "#a8b0b8", background = "#364446" }
focused_match = { foreground = "#a8b0b8", background = "#514c3f" }

[colors.hints]
start = { foreground = "#30302e", background = "#98c078" }
end = { foreground = "#30302e", background = "#5494c7" }

[colors.selection]
text = "CellForeground"
background = "#394752"

[colors.normal]
black = "#363635"
red = "#e06c75"
green = "#73905e"
yellow = "#c8b07a"
blue = "#528ab7"
magenta = "#a05a7f"
cyan = "#4b8b9a"
white = "#d0d6e0"

[colors.bright]
black = "#353637"
red = "#ff5f6b"
green = "#98c078"
yellow = "#d1a850"
blue = "#5494c7"
magenta = "#b06b90"
cyan = "#52aebb"
white = "#e0e5ef"

[colors.dim]
black = "#2d2d2b"
red = "#be737a"
green = "#637a52"
yellow = "#a89a78"
blue = "#3b4751"
magenta = "#8a6a7a"
cyan = "#5c7f88"
white = "#9098a0"
