[window]
opacity = 0.97
blur = true
decorations_theme_variant = "Dark"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background = "#24262b"
foreground = "#c0c8d2"
dim_foreground = "#9aa2ad"
bright_foreground = "#e0e5ef"

[colors.cursor]
text = "#24262b"
cursor = "#528ab7"

[colors.vi_mode_cursor]
text = "#24262b"
cursor = "#b98a5c"

[colors.search]
matches = { foreground = "#c0c8d2", background = "#30444c" }
focused_match = { foreground = "#c0c8d2", background = "#554f43" }

[colors.hints]
start = { foreground = "#24262b", background = "#98c078" }
end = { foreground = "#24262b", background = "#5494c7" }

[colors.selection]
text = "CellForeground"
background = "#364e63"

[colors.normal]
black = "#2b2e34"
red = "#e06c75"
green = "#73905e"
yellow = "#c8b07a"
blue = "#528ab7"
magenta = "#a05a7f"
cyan = "#4b8b9a"
white = "#d0d6e0"

[colors.bright]
black = "#31343c"
red = "#ff5f6b"
green = "#98c078"
yellow = "#d1a850"
blue = "#5494c7"
magenta = "#b06b90"
cyan = "#52aebb"
white = "#e0e5ef"

[colors.dim]
black = "#1f2126"
red = "#be737a"
green = "#637a52"
yellow = "#a89a78"
blue = "#3b4751"
magenta = "#8a6a7a"
cyan = "#5c7f88"
white = "#9aa2ad"
