[window]
opacity = 0.97
blur = true
decorations_theme_variant = "Dark"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background = "#0e1419"
foreground = "#d8dee9"
dim_foreground = "#a5abb6"
bright_foreground = "#eceff4"

[colors.cursor]
text = "#0e1419"
cursor = "#81a1c1"

[colors.vi_mode_cursor]
text = "#0e1419"
cursor = "#ffca28"

[colors.search]
matches = { foreground = "#0e1419", background = "#81a1c1" }
focused_match = { foreground = "#0e1419", background = "#ffca28" }

[colors.hints]
start = { foreground = "#0e1419", background = "#66bb6a" }
end = { foreground = "#0e1419", background = "#81a1c1" }

[colors.selection]
text = "CellForeground"
background = "#2e3440"

[colors.normal]
black = "#0e1419"
red = "#ef5350"
green = "#66bb6a"
yellow = "#ffca28"
blue = "#42a5f5"
magenta = "#ab47bc"
cyan = "#26c6da"
white = "#cfd8dc"

[colors.bright]
black = "#546e7a"
red = "#ff6b68"
green = "#81c784"
yellow = "#ffd54f"
blue = "#64b5f6"
magenta = "#ba68c8"
cyan = "#4dd0e1"
white = "#eceff1"

[colors.dim]
black = "#263238"
red = "#d32f2f"
green = "#388e3c"
yellow = "#f57c00"
blue = "#1976d2"
magenta = "#7b1fa2"
cyan = "#0097a7"
white = "#90a4ae"
