[window]
opacity = 1.0
blur = false
decorations_theme_variant = "Light"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background = "#fbfbfd"
foreground = "#383a42"
dim_foreground = "#6c6f77"
bright_foreground = "#282c34"

[colors.cursor]
text = "#fbfbfd"
cursor = "#4078f2"

[colors.vi_mode_cursor]
text = "#fbfbfd"
cursor = "#e77727"

[colors.search]
matches = { foreground = "#383a42", background = "#d8eaf4" }
focused_match = { foreground = "#383a42", background = "#f3eada" }

[colors.hints]
start = { foreground = "#fbfbfd", background = "#429b41" }
end = { foreground = "#fbfbfd", background = "#1f65ff" }

[colors.selection]
text = "CellForeground"
background = "#d6e1fb"

[colors.normal]
black = "#282c34"
red = "#e45649"
green = "#50a14f"
yellow = "#c18401"
blue = "#4078f2"
magenta = "#b751b6"
cyan = "#0184bc"
white = "#e5e5ea"

[colors.bright]
black = "#6c6f77"
red = "#f23726"
green = "#429b41"
yellow = "#ae7600"
blue = "#1f65ff"
magenta = "#b63db5"
cyan = "#0076a9"
white = "#f3f4f6"

[colors.dim]
black = "#8a8d96"
red = "#d3938d"
green = "#7ca87b"
yellow = "#c39532"
blue = "#8aa4db"
magenta = "#b685b5"
cyan = "#3195bf"
white = "#6c6f77"
